spring:
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB
  application:
    name: pruebadb
  jpa:
    hibernate:
      ddl-auto: validate
  datasource:
    url: jdbc:mysql://${DB_HOST}:3306/${DB_DATABASE}
    username: ${DB_USER}
    password: ${DB_PASS}
    hikari:
      maximum-pool-size: 10 #maximo conexion abrir
      minimum-idle: 5 #minimo conexiones abrir
      idleTimeout: 300000 # 5 minutos que puede estar en espera antes de cerrar la conexion
      connection-timeout: 100000
db:
  pass: ${DB_PASS}
  user: ${DB_USER}
  user_direct: link_direct

prueba:
  datasource:
    primary:
      url: jdbc:mysql://localhost:3306/primary_db
      username: user_primary
      password: pass_primary
      driver-class-name: com.mysql.cj.jdbc.Driver
    secondary:
      url: jdbc:mysql://localhost:3306/secondary_db
      username: user_secondary
      password: pass_secondary
      driver-class-name: com.mysql.cj.jdbc.Driver
