spring:
  application:
    name: pruebadb
  jpa:
    hibernate:
      ddl-auto: validate
  datasource:
    url: jdbc:mysql://${DB_HOST}:3306/${DB_DATABASE}
    username: ${DB_USER}
    password: ${DB_PASS}
    hikari:
      maximum-pool-size: 5 #maximo conexion abrir
      minimum-idle: 2 #minimo conexiones abrir
      idleTimeout: 300000 # 5 minutos que puede estar en espera antes de cerrar la conexion
db:
  pass: ${DB_PASS}
  user: ${DB_USER}

