spring:
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB
  application:
    name: pruebadb
  jpa:
    hibernate:
      ddl-auto: validate
  datasource:
    url: jdbc:mysql://${DB_HOST}:3306/${DB_DATABASE}
    username: ${DB_USER}
    password: ${DB_PASS}
    hikari:
      maximum-pool-size: 10 #maximo conexion abrir
      minimum-idle: 2 #minimo conexiones abrir
      idleTimeout: 300000 # 5 minutos que puede estar en espera antes de cerrar la conexion
      connection-timeout: 100000
db:
  pass: ${DB_PASS}
  user: ${DB_USER}

